const defaults={visions:[],visionPrompt:'',visionBrief:{life:'',visuals:'',feeling:'',style:''},goals:[],sessions:[],fuel:[],future:'',intention:'',action:'',cue:null,dailyReflections:[],weeklyReviews:[],celebration:null,setup:{dismissed:false}};
let data=JSON.parse(localStorage.getItem('manifestDataV18')||'null')||structuredClone(defaults);data.goals=(data.goals||[]).map((g,i)=>({...g,key:g.key??i<3,identity:g.identity||'',system:g.system||'',progress:0,tasks:(g.tasks||[]).map(t=>typeof t==='string'?{text:t,done:false}:{...t})}));if(!data.visions)data.visions=[];if(data.visionPrompt===undefined)data.visionPrompt='';if(!data.visionBrief)data.visionBrief={life:'',visuals:'',feeling:'',style:''};if(!data.sessions)data.sessions=[];if(!data.fuel)data.fuel=[];if(data.cue===undefined)data.cue=null;if(!data.dailyReflections)data.dailyReflections=[];if(!data.weeklyReviews)data.weeklyReviews=[];if(data.celebration===undefined)data.celebration=null;if(!data.future)data.future=defaults.future;if(!data.setup)data.setup={dismissed:false};let tab='dashboard',mstep=0,manswers=['','','','','',''];const steps=[['SEE','See the life you want.','Picture it as if you’re already there.'],['FEEL','Step into that future for a moment.','How does it feel to live this reality?'],['BELIEVE','Ground the belief.','Why is this possible for you? What evidence shows you can move toward it?'],['ALIGN','See the distance clearly.','What needs to change between where you are and where you want to be?'],['PLAN','Decide before the obstacle arrives.','If the main obstacle appears, then what will you do?'],['ACT','Bring the future into today.','What is one action you will take today?']];
function goalProgress(g){let t=g.tasks||[];return t.length?Math.round(t.filter(x=>x.done).length/t.length*100):0}const $=s=>document.querySelector(s);function save(){localStorage.setItem('manifestDataV18',JSON.stringify(data))}function esc(s=''){return String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}function lines(s=''){return String(s).split(/\n+/).map(x=>x.trim()).filter(Boolean)}function render(){document.querySelectorAll('nav button').forEach(b=>b.classList.toggle('active',b.dataset.tab===tab));({dashboard,vision,goals,manifest,fuel}[tab])()}
function dashboard(){let items=setupStatus(),next=items.findIndex(x=>!x.done),complete=next<0,current=complete?null:items[next];$('#view').innerHTML=`<div class="topline calmheader"><div><div class="welcome">Come build your life.</div><h1>Dashboard</h1></div><button class="avatar" onclick="settingsModal()">•••</button></div>${!complete?`<section class="nextstepcard"><div class="nextstepmeta"><span>STEP ${next+1} OF ${items.length}</span><b>${current.stage}</b></div><div class="nextstepbar">${items.map((x,i)=>`<i class="${x.done?'done':i===next?'current':''}"></i>`).join('')}</div><h2>${current.title}</h2><p>${current.desc}</p><button class="nextstepcta" onclick="journeyGo(${next})">${current.cta}<span>→</span></button><button class="quietlink" onclick="setupModal()">View the full journey</button></section>`:`<section class="foundationdone"><small>FOUNDATION COMPLETE</small><h2>Keep moving.</h2><p>Your setup is done. Choose one useful move for today.</p></section>`}<section class="todayonly"><div class="sectionhead"><h2>Today</h2></div><button class="todaycard cleantoday" onclick="editText('action','One action today')"><span><small>ONE MOVE</small>${esc(data.action||'Choose your next move')}</span><b>${data.action?'Edit':'+'}</b></button></section><button class="aboutfooter" onclick="aboutModal()">About MANIFEST · format & sources</button>`}
function vision(){let v=data.visions[0];$('#view').innerHTML=`<div class="vision30top"><div><div class="eyebrow">SEE IT CLEARLY</div><h1>Your Vision</h1></div>${v?`<button class="visionmenu" onclick="visionActions()">•••</button>`:''}</div>${v?`<section class="singlevision"><img data-vision-img="${v.id}" alt="Your Vision"><div class="visionactions"><button onclick="visionPromptScreen(true)">Refine Vision</button><button onclick="visionPromptScreen(false)">Generate another</button></div>${data.visionPrompt?`<button class="viewprompt" onclick="showSavedVisionPrompt()">View prompt</button>`:''}</section>`:`<section class="vision30empty"><div class="visionglow">✦</div><h2>Create one visual world for the life you want.</h2><p>Describe it once. Turn it into a single cohesive Vision board.</p><button class="primary30" onclick="visionPromptScreen(false)">Create my Vision</button><button class="quietlink" onclick="visionGuidedPrompts()">Need help writing it?</button></section>`}<input id="visionBoardFile" class="nativefile" type="file" accept="image/*" onchange="saveGeneratedVision(this)">`;hydrateVisionImages()}
function visionPromptScreen(refine=false){let current=data.visionPrompt||suggestVisionPrompt();openModal(`<div class="vision30prompt"><div class="eyebrow">YOUR VISION</div><h2>Describe the life you want to step into.</h2><p>Write freely. Include the life, feeling and visual world you want to see.</p><textarea id="visionPromptText" class="field visionbigfield" placeholder="A warm, cinematic visual board of the life I am building…">${esc(current)}</textarea><button class="primary30 modalprimary" onclick="prepareVisionPrompt()">Generate Vision</button><button class="secondary30" onclick="visionGuidedPrompts()">Use guided prompts</button>${data.goals.length?`<button class="quietlink" onclick="autoSuggestVision()">Suggest from my goals</button>`:''}</div>`)}
function suggestVisionPrompt(){let titles=data.goals.slice(0,5).map(g=>g.title).filter(Boolean);return titles.length?`Create a cohesive, cinematic visual board representing a life shaped by ${titles.join(', ')}. Make it warm, realistic, aspirational and emotionally grounded.`:''}
function autoSuggestVision(){let p=suggestVisionPrompt();let el=$('#visionPromptText');if(el){el.value=p;el.focus()}}
function visionGuidedPrompts(){let b=data.visionBrief||{};openModal(`<div class="vision30prompt"><div class="eyebrow">GUIDED VISION</div><h2>Build your prompt.</h2><p>Four short answers. That’s all.</p><label>What kind of life are you building?</label><textarea id="vblife" class="field" placeholder="Healthy, creative, secure, connected…">${esc(b.life||'')}</textarea><label>What should appear visually?</label><textarea id="vbvisuals" class="field" placeholder="Career, home, fitness, people, travel…">${esc(b.visuals||'')}</textarea><label>How should it feel?</label><input id="vbfeeling" class="field" value="${esc(b.feeling||'')}" placeholder="Warm, calm, powerful, hopeful"><label>Style / aesthetic</label><input id="vbstyle" class="field" value="${esc(b.style||'')}" placeholder="Cinematic, elegant, modern, editorial"><button class="primary30 modalprimary" onclick="buildGuidedVisionPrompt()">Create prompt</button></div>`)}
function buildGuidedVisionPrompt(){let b={life:$('#vblife').value.trim(),visuals:$('#vbvisuals').value.trim(),feeling:$('#vbfeeling').value.trim(),style:$('#vbstyle').value.trim()};data.visionBrief=b;data.visionPrompt=`Create one cohesive visual Vision board representing ${b.life||'the life I want to build'}. Include visual elements such as ${b.visuals||'the people, places and experiences that matter to me'}. The overall mood should feel ${b.feeling||'warm, hopeful and grounded'}. Use a ${b.style||'cinematic, elegant and realistic'} aesthetic. Make the image aspirational but believable, with a unified composition rather than separate collage tiles.`;save();visionPromptScreen(true)}
function prepareVisionPrompt(){let p=$('#visionPromptText').value.trim();if(!p){alert('Describe the Vision you want to create.');return}data.visionPrompt=p;save();openModal(`<div class="visionready"><div class="eyebrow">VISION READY</div><h2>Your image prompt is ready.</h2><p>This GitHub Pages build keeps your prompt and finished board private on your device. To create the image, use the prompt with an image generator, then add the finished image here.</p><div class="promptpreview">${esc(p)}</div><button class="primary30 modalprimary" onclick="copyVisionPrompt()">Copy AI prompt</button><button class="secondary30" onclick="chooseGeneratedVision()">Add generated board</button><button class="quietlink" onclick="visionPromptScreen(true)">Refine prompt</button></div>`)}
async function copyVisionPrompt(){try{await navigator.clipboard.writeText(data.visionPrompt);toast('Vision prompt copied')}catch(e){alert(data.visionPrompt)}}
function chooseGeneratedVision(){closeModal();let f=$('#visionBoardFile');if(f)f.click()}
async function saveGeneratedVision(input){let file=input.files&&input.files[0];if(!file)return;let old=data.visions[0],id=Date.now();try{await putVisionImage(id,file);if(old)await deleteVisionImage(old.id).catch(()=>{});data.visions=[{id,height:520,size:'v2',posx:50,posy:50,zoom:1}];save();input.value='';render();toast('Vision saved')}catch(e){console.error(e);alert('MANIFEST could not save that image. Please try again.')}}
function showSavedVisionPrompt(){openModal(`<div class="visionready"><div class="eyebrow">YOUR VISION PROMPT</div><h2>The words behind the board.</h2><div class="promptpreview">${esc(data.visionPrompt||'')}</div><button class="primary30 modalprimary" onclick="copyVisionPrompt()">Copy prompt</button></div>`)}
function visionActions(){openModal(`<div class="visionactionsmenu"><div class="eyebrow">YOUR VISION</div><h2>What would you like to do?</h2><button class="toolchoice" onclick="closeModal();visionPromptScreen(true)"><strong>Refine Vision</strong><span>Edit the prompt and create a new version.</span></button><button class="toolchoice" onclick="closeModal();visionPromptScreen(false)"><strong>Generate another</strong><span>Start from a fresh prompt.</span></button><button class="secondary danger" onclick="removeVisionBoard()">Remove Vision</button></div>`)}
async function removeVisionBoard(){let v=data.visions[0];if(v)await deleteVisionImage(v.id).catch(()=>{});data.visions=[];data.visionPrompt='';save();closeModal();render()}
function visionDB(){return new Promise((resolve,reject)=>{let r=indexedDB.open('manifestVisionImages',1);r.onupgradeneeded=()=>r.result.createObjectStore('images');r.onsuccess=()=>resolve(r.result);r.onerror=()=>reject(r.error)})}
async function putVisionImage(id,file){let db=await visionDB();return new Promise((resolve,reject)=>{let tx=db.transaction('images','readwrite');tx.objectStore('images').put(file,String(id));tx.oncomplete=resolve;tx.onerror=()=>reject(tx.error)})}
async function getVisionImage(id){let db=await visionDB();return new Promise((resolve,reject)=>{let r=db.transaction('images').objectStore('images').get(String(id));r.onsuccess=()=>resolve(r.result);r.onerror=()=>reject(r.error)})}
async function deleteVisionImage(id){let db=await visionDB();return new Promise((resolve,reject)=>{let tx=db.transaction('images','readwrite');tx.objectStore('images').delete(String(id));tx.oncomplete=resolve;tx.onerror=()=>reject(tx.error)})}
async function hydrateVisionImages(){for(let el of document.querySelectorAll('[data-vision-img]')){try{let blob=await getVisionImage(el.dataset.visionImg);if(blob){let u=URL.createObjectURL(blob);el.src=u;el.onload=()=>URL.revokeObjectURL(u)}}catch(e){console.error(e)}}}
function toast(msg){let t=document.createElement('div');t.className='toast';t.textContent=msg;document.body.appendChild(t);setTimeout(()=>t.remove(),1800)}
function goalCard(g,compact=false){let pct=goalProgress(g),tasks=g.tasks||[],done=tasks.filter(t=>t.done).length;return `<div class="card goalcard goalcard-elevated" onclick="goalDetail(${g.id})"><div class="goalmeta"><span class="eyebrow">${esc(g.vision||'Goal')}</span>${g.key?'<span class="keytag">KEY</span>':''}</div><div class="goalrow"><strong>${esc(g.title)}</strong><span>${pct}%</span></div><div class="progress"><i style="width:${pct}%"></i></div><div class="nextline"><span class="muted">Tasks</span><span>${done}/${tasks.length} complete</span></div>${compact?'':'<div class="viewplan">Open action plan →</div>'}</div>`}
function goals(){let key=data.goals.filter(g=>g.key),other=data.goals.filter(g=>!g.key);let keyHtml=key.length?key.map(g=>goalCard(g)).join(''):`<button class="emptygoal" onclick="goalModal()"><span>Add your first goal</span><b>+</b></button>`;let otherHtml=other.length?`<div class="sectionhead othergoalshead"><h2>Other goals</h2></div>${other.map(g=>goalCard(g)).join('')}`:'';$('#view').innerHTML=`<div class="topline"><div><div class="eyebrow">What I'm making real</div><h1>Goals</h1></div><button class="roundadd" onclick="goalModal()">+</button></div><div class="sectionhead"><h2>Key Goals</h2><span class="pill">${key.length}/5</span></div>${keyHtml}${otherHtml}`}
function goalDetail(id){let g=data.goals.find(x=>x.id===id);if(!g)return;let tasks=g.tasks||[],pct=goalProgress(g),active=tasks.map((t,i)=>({...t,_i:i})).filter(t=>!t.done),completed=tasks.map((t,i)=>({...t,_i:i})).filter(t=>t.done);openModal(`<div class="compactplan"><div class="compacthead"><div><div class="eyebrow">Goal</div><h2>${esc(g.title)}</h2></div><strong>${pct}%</strong></div><div class="progress"><i style="width:${pct}%"></i></div>${g.why?`<div class="compactrow"><b>Why it matters</b><span>${esc(g.why)}</span></div>`:''}${g.identity?`<div class="identitybox"><small>WHO I’M BECOMING</small><strong>${esc(g.identity)}</strong></div>`:''}<div class="compacttasks"><div class="compactlabel"><b>Steps</b><button onclick="addTask(${g.id})">+</button></div>${active.length?active.map(t=>`<label><input type="checkbox" onchange="toggleTask(${g.id},${t._i},this.checked)"><span>${esc(t.text)}</span></label>`).join(''):(completed.length?'':'<span class="muted">No steps yet.</span>')}${completed.length?`<details class="completedsteps"><summary>COMPLETED · ${completed.length}</summary>${completed.map(t=>`<label><input type="checkbox" checked onchange="toggleTask(${g.id},${t._i},this.checked)"><span class="taskdone">${esc(t.text)}</span></label>`).join('')}</details>`:''}</div><div class="compactactions smallactions"><button class="secondary" onclick="goalModal(${g.id})">Edit goal</button><button class="secondary subtleaction" onclick="toggleKey(${g.id})">${g.key?'Remove Key Goal':'Make Key Goal'}</button></div></div>`)}
function toggleTask(id,i,done){let g=data.goals.find(x=>x.id===id);if(!g||!g.tasks?.[i])return;g.tasks[i].done=done;g.progress=goalProgress(g);save();closeModal();goalDetail(id)}function addTask(id){let text=prompt('What action needs to be completed?');if(!text?.trim())return;let g=data.goals.find(x=>x.id===id);g.tasks=g.tasks||[];g.tasks.push({text:text.trim(),done:false});g.progress=goalProgress(g);save();closeModal();goalDetail(id)}
function manifest(){let c=data.celebration,days=c?.date?daysUntil(c.date):null;$('#view').innerHTML=`<div class="manifesthome manifest30"><div class="eyebrow">OPTIONAL PRACTICES</div><h1>Use what helps.</h1><p class="muted">These are tools, not homework.</p><button class="manifesthero compactmanifesthero" onclick="startManifestSession()"><small>GUIDED VISUALISATION</small><strong>See it clearly</strong><span>A short future-focused session.</span><b>Start ›</b></button><button class="manifestexercise" onclick="sixMonthDinner()"><div><small>FUTURE MOMENT</small><strong>Six Months From Now</strong><span>${c?.date?(days>=0?days+' days away':'Date saved'):'Set an “Everything Worked Out” dinner'}</span></div><b>›</b></button><button class="manifestexercise" onclick="cueModal()"><div><small>MENTAL CUE</small><strong>${data.cue?.statement?'Change my cue':'Create a mental cue'}</strong><span>Link a useful thought to a real-life trigger.</span></div><b>›</b></button><button class="manifestexercise" onclick="reflectionTools()"><div><small>REFLECT</small><strong>Reflect & adjust</strong><span>Daily or weekly, only when useful.</span></div><b>›</b></button></div>`}
function startManifestSession(){mstep=0;manifestSession()}
function manifestSession(){let [name,title,prompt]=steps[mstep];$('#view').innerHTML=`<div class="manifest-stage"><div class="stepnum">${mstep+1} / ${steps.length} · ${name}</div><h1>${title}</h1><p class="muted">${prompt}</p><textarea id="mans" class="field" placeholder="Write freely…">${esc(manswers[mstep])}</textarea><button class="primary compactcta" onclick="nextManifest()">${mstep===steps.length-1?'Complete & carry it forward':'Continue'}</button>${mstep?'<button class="secondary" onclick="prevManifest()">Back</button>':''}</div>`}
function go(t){tab=t;mstep=t==='manifest'?0:mstep;closeModal();render()}document.querySelectorAll('nav button').forEach(b=>b.onclick=()=>go(b.dataset.tab));$('#enter').onclick=()=>{$('#splash').classList.add('hidden');$('#app').classList.remove('hidden');render();maybeSetup()};
function openModal(html){$('#modalBody').innerHTML=html;$('#modal').classList.remove('hidden')}function closeModal(){$('#modal').classList.add('hidden')}function editText(key,title){openModal(`<h2>${title}</h2><textarea id="txt" class="field">${esc(data[key])}</textarea><button class="primary" onclick="data['${key}']=$('#txt').value;save();closeModal();render()">Save</button>`)}
function aboutModal(){openModal(`<div class="aboutmodal"><div class="eyebrow">ABOUT MANIFEST</div><h2>See it. Choose it. Live it.</h2><p>MANIFEST is a practical framework for turning a picture of the life you want into clearer priorities and the next action you can take.</p><div class="aboutflow aboutflow7"><span>SEE</span><i>→</i><span>DEFINE</span><i>→</i><span>PRIORITISE</span><i>→</i><span>BECOME</span><i>→</i><span>PLAN</span><i>→</i><span>ACT</span><i>→</i><span>REFLECT</span></div><h3>How the format works</h3><p><strong>Vision</strong> keeps the destination visible. <strong>Goals</strong> make it concrete. <strong>Priorities</strong> narrow the focus. <strong>Identity</strong> asks who you are becoming. <strong>Steps</strong> make action obvious. <strong>Reflection</strong> helps you adjust.</p><h3>Ideas that informed it</h3><p>MANIFEST adapts broad ideas from behaviour change, goal setting, mental rehearsal and reflection, including principles popularised in <em>Atomic Habits</em> by James Clear, <em>The 7 Habits of Highly Effective People</em> by Stephen R. Covey, and <em>The Miracle Morning</em> by Hal Elrod, plus practical exercises developed during the design process.</p><p class="aboutnote">This is an original personal planning framework, not an official companion to or endorsement by those authors or books.</p><div class="versionlabel">MANIFEST 3.0</div><button class="primary30 modalprimary" onclick="closeModal()">Done</button></div>`)}
function settingsModal(){openModal(`<div class="eyebrow">MANIFEST</div><h2>Settings</h2><button class="secondary" onclick="aboutModal()">About MANIFEST</button><button class="secondary" onclick="exportData()">Export my data</button><button class="secondary" onclick="resetData()">Reset app data</button>`)}
async function visionModal(id){let v=data.visions.find(x=>x.id===id);if(!v)return;let blob=await getVisionImage(id),url=blob?URL.createObjectURL(blob):'';openModal(`<h2>Edit image</h2><div class="imagepreview"><img id="visionPreviewImg" src="${url}" alt=""></div><input id="vfile" type="file" accept="image/*" class="filepick"><button class="secondary" onclick="$('#vfile').click()">Replace photo</button><div class="resizegrid"><label>Width<select id="vsize" class="field"><option value="v1" ${v.size!=='v2'?'selected':''}>1 column</option><option value="v2" ${v.size==='v2'?'selected':''}>2 columns</option></select></label><label>Height<input id="vheight" type="range" min="140" max="520" value="${v.height||215}" oninput="updateVisionPreview()"></label></div><label>Zoom</label><input id="vzoom" type="range" min="1" max="2.5" step="0.05" value="${v.zoom||1}" oninput="updateVisionPreview()"><label>Horizontal</label><input id="vposx" type="range" min="0" max="100" value="${v.posx??50}" oninput="updateVisionPreview()"><label>Vertical</label><input id="vposy" type="range" min="0" max="100" value="${v.posy??50}" oninput="updateVisionPreview()"><button class="primary red" onclick="saveVision(${id})">Save</button><button class="secondary danger" onclick="deleteVision(${id})">Delete</button>`);$('#vfile').onchange=async function(){let f=this.files&&this.files[0];if(!f)return;this._newFile=f;let u=URL.createObjectURL(f);$('#visionPreviewImg').src=u};updateVisionPreview()}
function updateVisionPreview(){let im=$('#visionPreviewImg');if(!im)return;im.style.objectPosition=($('#vposx')?.value||50)+'% '+($('#vposy')?.value||50)+'%';im.style.transform=`scale(${$('#vzoom')?.value||1})`;let box=im.parentElement;box.style.height=($('#vheight')?.value||250)+'px'}
async function saveVision(id){let old=data.visions.find(x=>x.id===id);if(!old)return;let f=$('#vfile');try{if(f?._newFile)await putVisionImage(id,f._newFile);let v={...old,posx:Number($('#vposx').value||50),posy:Number($('#vposy').value||50),zoom:Number($('#vzoom').value||1),height:Number($('#vheight').value||215),size:$('#vsize').value||'v1'};data.visions=data.visions.map(x=>x.id===id?v:x);save();closeModal();render();toast('Vision updated')}catch(e){alert('Could not save this photo.')}}
async function deleteVision(id){data.visions=data.visions.filter(x=>x.id!==id);save();try{await deleteVisionImage(id)}catch(e){}closeModal();render()}
function visionToGoal(id){let v=data.visions.find(x=>x.id===id);closeModal();goalModal(0,v?.title||v?.desc||'')}
function goalModal(id,linked=''){let g=data.goals.find(x=>x.id===id)||{title:'',why:'',identity:'',tasks:[],key:data.goals.filter(x=>x.key).length<5};openModal(`<div class="eyebrow">${id?'EDIT GOAL':'CREATE GOAL'}</div><h2>${id?'Keep it clear.':'What are you making real?'}</h2><label>Goal</label><input id="gt" class="field" value="${esc(g.title)}" placeholder="What do you want?"><label>Why it matters</label><textarea id="gw" class="field" placeholder="Why does this matter to you?">${esc(g.why||'')}</textarea><label>Who I’m becoming <span class="optionalword">Optional</span></label><input id="gidentity" class="field" value="${esc(g.identity||'')}" placeholder="I’m becoming someone who…"><label>Steps</label><textarea id="gtasks" class="field" placeholder="One clear step per line">${esc((g.tasks||[]).map(t=>t.text).join('\n'))}</textarea><label class="checkrow"><input id="gkey" type="checkbox" ${g.key?'checked':''}> <span>Key Goal</span></label><button class="primary red" onclick="saveGoal(${id||0})">${id?'Save':'Create goal'}</button>${id?`<button class="secondary danger" onclick="deleteGoal(${id})">Delete goal</button>`:''}`)}
function saveGoal(id){let key=$('#gkey').checked;if(key&&!data.goals.find(x=>x.id===id)?.key&&data.goals.filter(x=>x.key).length>=5){alert('Choose up to 5 Key Goals.');return}let old=data.goals.find(x=>x.id===id),oldDone=new Map((old?.tasks||[]).map(t=>[t.text,!!t.done]));let g={...(old||{}),id:id||Date.now(),title:$('#gt').value||'Untitled Goal',why:$('#gw').value,identity:$('#gidentity')?.value.trim()||'',system:'',tasks:lines($('#gtasks').value).map(text=>({text,done:oldDone.get(text)||false})),key};if(id)data.goals=data.goals.map(x=>x.id===id?g:x);else data.goals.push(g);save();closeModal();render()}
function deleteGoal(id){data.goals=data.goals.filter(x=>x.id!==id);save();closeModal();render()}function toggleKey(id){let g=data.goals.find(x=>x.id===id);if(!g)return;if(!g.key&&data.goals.filter(x=>x.key).length>=5){alert('Choose up to 5 Key Goals for this chapter.');return}g.key=!g.key;save();closeModal();render()}function carryAction(id){let g=data.goals.find(x=>x.id===id);if(g?.next){data.action=g.next;save()}closeModal();tab='dashboard';render()}
function nextManifest(){manswers[mstep]=$('#mans').value;if(mstep<5){mstep++;manifestSession()}else{data.sessions.unshift({date:new Date().toLocaleDateString(),answers:[...manswers]});data.action=manswers[5]||data.action;save();manswers=['','','','','',''];mstep=0;openModal(`<div class="eyebrow">SEE · BELIEVE · ALIGN · ACT</div><h2>Carry it into your life.</h2><p class="quote">The vision matters because of what you do next.</p><div class="plansection nextaction"><div class="eyebrow">Today</div><strong>${esc(data.action||'No action chosen yet.')}</strong></div><button class="primary" onclick="closeModal();go('dashboard')">Go to Dashboard</button>`)}}function prevManifest(){manswers[mstep]=$('#mans').value;mstep--;manifestSession()}
function exportData(){let blob=new Blob([JSON.stringify(data,null,2)],{type:'application/json'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='manifest-data.json';a.click();URL.revokeObjectURL(a.href)}function resetData(){if(confirm('Reset all MANIFEST data?')){localStorage.removeItem('manifestDataV18');data=structuredClone(defaults);closeModal();render()}}
function fuel(){let cards=data.fuel.map((x,i)=>fuelTile(x,i)).join('');$('#view').innerHTML=`<div class="fueltop"><div><h1>Fuel</h1><p>Use it.</p></div><div class="fuelheadbuttons">${data.fuel.length?`<button class="fuelsecondary" id="fuelEditBtn" onclick="toggleFuelEdit()">${fuelEditMode?'Done':'Edit board'}</button>`:''}<button class="roundadd fueladd" onclick="fuelModal()">+</button></div></div>${data.fuel.length?`<div class="fuelboard freefuelboard">${cards}</div>`:`<button class="fuelempty" onclick="fuelModal()"><span>+</span><strong>Add your first fuel</strong><small>Quote · Incident · Image</small></button>`}<input id="fuelQuickImage" type="file" accept="image/*" class="filepick">`;hydrateFuelImages();setTimeout(initFuelBoard,0)}
function fuelTile(x,i){let cls=`fueltile fuel-${x.type||'incident'} ${(i%5===0||i%7===3)?'fueltall':''}`;if(x.type==='image')return `<button class="${cls}" data-fuel-id="${x.id}" onclick="fuelTileClick(${x.id})"><img data-fuel-img="${x.id}" alt="Fuel image"><span class="fuelresize" aria-hidden="true"></span></button>`;let label=x.type==='quote'?'QUOTE':'INCIDENT';return `<button class="${cls}" data-fuel-id="${x.id}" onclick="fuelTileClick(${x.id})"><small>${label}</small><strong>${esc(x.what||'')}</strong><span class="fuelresize" aria-hidden="true"></span></button>`}
let fuelEditMode=false;
function fuelTileClick(id){if(fuelEditMode)return;fuelDetail(id)}
function getFuelLayout(){try{return JSON.parse(localStorage.getItem('manifestFuelLayout')||'{}')}catch(e){return {}}}
function saveFuelLayout(v){localStorage.setItem('manifestFuelLayout',JSON.stringify(v))}
function toggleFuelEdit(){fuelEditMode=!fuelEditMode;let b=$('.freefuelboard'),btn=$('#fuelEditBtn');if(b)b.classList.toggle('editing',fuelEditMode);if(btn)btn.textContent=fuelEditMode?'Done':'Edit board';initFuelBoard()}
function initFuelBoard(){let b=$('.freefuelboard');if(!b)return;b.classList.add('freeform');b.classList.toggle('editing',fuelEditMode);let layout=getFuelLayout(),cards=[...b.querySelectorAll('.fueltile')];cards.forEach((el,n)=>{let id=el.dataset.fuelId,p=layout[id]||{x:(n%2)*51,y:Math.floor(n/2)*230,w:48,h:(el.classList.contains('fuel-image')?(el.classList.contains('fueltall')?250:190):(el.classList.contains('fueltall')?220:170)),z:n+1};el.style.left=p.x+'%';el.style.top=p.y+'px';el.style.width=p.w+'%';el.style.height=p.h+'px';el.style.zIndex=p.z||n+1;const persist=()=>{layout[id]={x:parseFloat(el.style.left)||0,y:parseFloat(el.style.top)||0,w:parseFloat(el.style.width)||48,h:parseFloat(el.style.height)||170,z:parseInt(el.style.zIndex)||1};saveFuelLayout(layout);resizeFuelBoard()};el.onpointerdown=e=>{if(!fuelEditMode||e.target.classList.contains('fuelresize'))return;e.preventDefault();e.stopPropagation();let br=b.getBoundingClientRect(),er=el.getBoundingClientRect(),sx=e.clientX,sy=e.clientY,sl=er.left-br.left,st=er.top-br.top;el.style.zIndex=Math.max(1,...cards.map(c=>parseInt(c.style.zIndex)||1))+1;try{el.setPointerCapture(e.pointerId)}catch{}el.onpointermove=ev=>{let nx=Math.max(0,Math.min(br.width-er.width,sl+ev.clientX-sx)),ny=Math.max(0,st+ev.clientY-sy);el.style.left=(nx/br.width*100)+'%';el.style.top=ny+'px'};el.onpointerup=()=>{el.onpointermove=null;el.onpointerup=null;persist()}};let h=el.querySelector('.fuelresize');if(h)h.onpointerdown=e=>{if(!fuelEditMode)return;e.preventDefault();e.stopPropagation();let br=b.getBoundingClientRect(),er=el.getBoundingClientRect(),sx=e.clientX,sy=e.clientY,sw=er.width,sh=er.height;try{h.setPointerCapture(e.pointerId)}catch{}h.onpointermove=ev=>{let nw=Math.max(120,Math.min(br.width,sw+ev.clientX-sx)),nh=Math.max(110,sh+ev.clientY-sy);el.style.width=(nw/br.width*100)+'%';el.style.height=nh+'px'};h.onpointerup=()=>{h.onpointermove=null;h.onpointerup=null;persist()}}});resizeFuelBoard()}
function resizeFuelBoard(){let b=$('.freefuelboard');if(!b)return;let cards=[...b.querySelectorAll('.fueltile')],bottom=cards.reduce((m,c)=>Math.max(m,(parseFloat(c.style.top)||0)+(parseFloat(c.style.height)||c.offsetHeight)),340);b.style.minHeight=(bottom+36)+'px'}
function fuelModal(type='quote'){openModal(`<div class="eyebrow">Add Fuel</div><h2>What will push you?</h2><div class="fueltypes"><button class="${type==='quote'?'active':''}" onclick="fuelModal('quote')">Quote</button><button class="${type==='incident'?'active':''}" onclick="fuelModal('incident')">Incident</button><button class="${type==='image'?'active':''}" onclick="fuelModal('image')">Image</button></div>${type==='image'?`<input id="fuelimage" type="file" accept="image/*" class="nativefile"><label for="fuelimage" class="fuelimagepick"><span>＋</span><strong>Choose image or screenshot</strong><small id="fuelFileName">Photo Library · Take Photo · Choose File</small></label>`:`<label>${type==='quote'?'Quote':'What happened'}</label><textarea id="fuelwhat" class="field" placeholder="${type==='quote'?'Paste or write the words':'Write the incident'}"></textarea>`}<label>How I’ll use it <span class="optional">Optional</span></label><textarea id="fuelhow" class="field" placeholder="Add a response only if you want to"></textarea><button class="primary red" onclick="saveFuel('${type}')">Add to Fuel</button>`);if(type==='image'){let fi=$('#fuelimage');if(fi)fi.addEventListener('change',()=>{let f=fi.files&&fi.files[0];let n=$('#fuelFileName');if(f&&n)n.textContent='Selected: '+f.name})}}
async function saveFuel(type){let how=$('#fuelhow')?.value.trim()||'',id=Date.now();if(type==='image'){let file=$('#fuelimage')?.files?.[0];if(!file){alert('Choose an image or screenshot first.');return}try{await putFuelImage(id,file)}catch(e){console.error(e);alert('MANIFEST could not save that image on this device.');return}data.fuel.unshift({id,type:'image',how})}else{let what=$('#fuelwhat')?.value.trim()||'';if(!what)return;data.fuel.unshift({id,type,what,how})}save();closeModal();render();toast('Added to Fuel')}
function fuelDetail(id){let x=data.fuel.find(v=>v.id===id);if(!x)return;let body=x.type==='image'?`<div class="fueldetailimage"><img data-fuel-detail="${x.id}" alt=""></div>`:`<div class="fueldetailtext"><div class="eyebrow">${x.type==='quote'?'Quote':'Incident'}</div><strong>${esc(x.what||'')}</strong></div>`;openModal(`<div class="fuelentrydetail">${body}${x.how?`<div class="fuelresponse"><small>HOW I’LL USE IT</small><p>${esc(x.how)}</p></div>`:''}<button class="secondary danger" onclick="deleteFuel(${x.id})">Delete</button></div>`);if(x.type==='image')hydrateFuelDetail(x.id)}
async function deleteFuel(id){let x=data.fuel.find(v=>v.id===id);data.fuel=data.fuel.filter(v=>v.id!==id);save();if(x?.type==='image')try{await deleteFuelImage(id)}catch(e){}closeModal();render()}
function fuelDB(){return new Promise((resolve,reject)=>{let r=indexedDB.open('manifestFuelImages',1);r.onupgradeneeded=()=>r.result.createObjectStore('images');r.onsuccess=()=>resolve(r.result);r.onerror=()=>reject(r.error)})}
async function putFuelImage(id,file){let db=await fuelDB();return new Promise((resolve,reject)=>{let tx=db.transaction('images','readwrite');tx.objectStore('images').put(file,String(id));tx.oncomplete=resolve;tx.onerror=()=>reject(tx.error)})}
async function getFuelImage(id){let db=await fuelDB();return new Promise((resolve,reject)=>{let r=db.transaction('images').objectStore('images').get(String(id));r.onsuccess=()=>resolve(r.result);r.onerror=()=>reject(r.error)})}
async function deleteFuelImage(id){let db=await fuelDB();return new Promise((resolve,reject)=>{let tx=db.transaction('images','readwrite');tx.objectStore('images').delete(String(id));tx.oncomplete=resolve;tx.onerror=()=>reject(tx.error)})}
async function hydrateFuelImages(){for(let el of document.querySelectorAll('[data-fuel-img]')){try{let blob=await getFuelImage(el.dataset.fuelImg);if(blob){let u=URL.createObjectURL(blob);el.src=u;el.onload=()=>URL.revokeObjectURL(u)}}catch(e){console.error(e)}}}
async function hydrateFuelDetail(id){let el=document.querySelector(`[data-fuel-detail="${id}"]`);if(!el)return;try{let blob=await getFuelImage(id);if(blob){let u=URL.createObjectURL(blob);el.src=u;el.onload=()=>URL.revokeObjectURL(u)}}catch(e){console.error(e)}}
function setupStatus(){let key=data.goals.filter(g=>g.key).slice(0,5),identityGoal=key.find(g=>g.identity?.trim()),pathGoal=key.find(g=>(g.tasks||[]).length);return [
 {stage:'SEE',title:'Create your Vision',desc:'Turn the life you want into one visual world you can return to.',cta:'Create my Vision',done:data.visions.length>=1,go:()=>go('vision')},
 {stage:'DEFINE',title:'Define what matters',desc:'Turn that Vision into your first concrete goal.',cta:'Create my first goal',done:data.goals.length>=1,go:()=>go('goals')},
 {stage:'PRIORITISE',title:'Choose what matters most',desc:'Pick 3–5 Key Goals for this chapter of your life.',cta:'Choose my Key Goals',done:key.length>=3,go:()=>go('goals')},
 {stage:'BECOME',title:'Decide who you’re becoming',desc:'For one Key Goal, finish “I’m becoming someone who…”',cta:'Define who I’m becoming',done:!!identityGoal,go:()=>key[0]?goalModal(key[0].id):go('goals')},
 {stage:'PLAN',title:'Build the next steps',desc:'Give a Key Goal clear steps so action is obvious.',cta:'Build my steps',done:!!pathGoal,go:()=>key[0]?goalModal(key[0].id):go('goals')},
 {stage:'ACT',title:'Choose today’s move',desc:'Choose one concrete action that moves you forward today.',cta:'Choose today’s move',done:!!data.action?.trim(),go:()=>editText('action','One action today')},
 {stage:'REFLECT',title:'Reflect and adjust',desc:'Complete one quick reflection so the system can learn with you.',cta:'Reflect on today',done:(data.dailyReflections||[]).length>0,go:()=>dailyReflection()}
]}
function journeyGo(i){let x=setupStatus()[i];if(x)x.go()}
function setupModal(){let items=setupStatus(),done=items.filter(x=>x.done).length,next=items.findIndex(x=>!x.done);openModal(`<div class="journey30"><div class="journey30head"><div class="eyebrow">YOUR JOURNEY</div><h2>${next<0?'Foundation complete':'Step '+(next+1)+' of '+items.length}</h2><p>${next<0?'You’ve built the foundation. Keep using the app when it helps.':'Focus only on the highlighted step.'}</p><div class="journey30bar"><i style="width:${Math.round(done/items.length*100)}%"></i></div></div><div class="journey30list">${items.map((x,i)=>{let current=i===next,future=next>=0&&i>next&&!x.done;return `<div class="journey30row ${x.done?'done':''} ${current?'current':''} ${future?'future':''}"><span class="journey30num">${x.done?'✓':i+1}</span><div><small>${x.stage}${current?' · YOU ARE HERE':''}</small><strong>${x.title}</strong></div></div>`}).join('')}</div>${next>=0?`<button class="journey30cta" onclick="setupGo(${next})">Continue with Step ${next+1}<span>→</span></button>`:`<button class="journey30cta" onclick="closeModal();go('dashboard')">Back to Dashboard<span>→</span></button>`}</div>`)}
function setupGo(i){let item=setupStatus()[i];closeModal();item&&item.go()}
function setupContinue(){let items=setupStatus(),next=items.findIndex(x=>!x.done);closeModal();if(next>=0)items[next].go();else{data.setup.dismissed=true;save();go('dashboard')}}
function cueModal(){let c=data.cue||{};openModal(`<div class="cuemodal"><div class="eyebrow">MENTAL CUE</div><h2>Make the thought easier to remember.</h2><p>Attach one useful statement to something you already do in real life.</p><label>When I…</label><input id="cuetrigger" class="field" value="${esc(c.trigger||'')}" placeholder="walk through a doorway"><div class="cuepresets"><button onclick="setCueTrigger('walk through a doorway')">Doorway</button><button onclick="setCueTrigger('get in the car')">Car</button><button onclick="setCueTrigger('start work')">Work</button><button onclick="setCueTrigger('look in the mirror')">Mirror</button><button onclick="setCueTrigger('start training')">Training</button><button onclick="setCueTrigger('prepare to perform')">Performance</button></div><label>I remind myself…</label><textarea id="cuestatement" class="field" placeholder="Trust your timing.">${esc(c.statement||'')}</textarea><div class="cueexamples"><small>Keep it short, useful and believable.</small></div><button class="primary red" onclick="saveCue()">Save mental cue</button>${c.statement?`<button class="secondary cueclear" onclick="clearCue()">Remove cue</button>`:''}</div>`)}
function setCueTrigger(v){let el=$('#cuetrigger');if(el){el.value=v;el.focus()}}
function saveCue(){let trigger=$('#cuetrigger').value.trim(),statement=$('#cuestatement').value.trim();if(!trigger||!statement){alert('Add both a trigger and a reminder.');return}data.cue={trigger,statement};save();closeModal();toast('Mental cue saved');render()}
function clearCue(){data.cue=null;save();closeModal();render()}
function daysUntil(dateStr){let a=new Date(),b=new Date(dateStr+'T12:00:00');a.setHours(12,0,0,0);return Math.ceil((b-a)/86400000)}
function defaultCelebrationDate(){let d=new Date();d.setMonth(d.getMonth()+6);while(d.getDay()!==5)d.setDate(d.getDate()+1);return d.toISOString().slice(0,10)}
function reflectionTools(){openModal(`<div class="reflectionchooser"><div class="eyebrow">REFLECT & ADJUST</div><h2>What do you need?</h2><button class="toolchoice" onclick="closeModal();dailyReflection()"><strong>Quick reflection</strong><span>What went well, what moved me forward, what changes tomorrow.</span></button><button class="toolchoice" onclick="closeModal();weeklyReset()"><strong>Weekly reset</strong><span>Review the week and choose what matters next.</span></button></div>`)}
function dailyReflection(){openModal(`<div class="reflectionmodal"><div class="eyebrow">REFLECT · DAILY</div><h2>Learn from today.</h2><label>What went well?</label><textarea id="dr1" class="field" placeholder="A win, however small…"></textarea><label>What moved me forward?</label><textarea id="dr2" class="field" placeholder="What actually helped?"></textarea><label>What will I change tomorrow?</label><textarea id="dr3" class="field" placeholder="One adjustment…"></textarea><button class="primary red" onclick="saveDailyReflection()">Save reflection</button></div>`)}
function saveDailyReflection(){let entry={id:Date.now(),date:new Date().toLocaleDateString(),went:$('#dr1').value.trim(),moved:$('#dr2').value.trim(),change:$('#dr3').value.trim()};if(!entry.went&&!entry.moved&&!entry.change)return;data.dailyReflections.unshift(entry);save();closeModal();toast('Reflection saved')}
function weeklyReset(){openModal(`<div class="reflectionmodal"><div class="eyebrow">REFLECT → ADJUST</div><h2>Weekly Reset</h2><label>Biggest win</label><textarea id="wr1" class="field" placeholder="What are you proud of?"></textarea><label>Biggest lesson</label><textarea id="wr2" class="field" placeholder="What did the week teach you?"></textarea><label>What got in the way?</label><textarea id="wr3" class="field" placeholder="Patterns, distractions, obstacles…"></textarea><label>What matters most next week?</label><textarea id="wr4" class="field" placeholder="Choose the priority."></textarea><label>One adjustment</label><input id="wr5" class="field" placeholder="Start, stop or change one thing"><button class="primary red" onclick="saveWeeklyReset()">Save & recalibrate</button></div>`)}
function saveWeeklyReset(){let entry={id:Date.now(),date:new Date().toLocaleDateString(),win:$('#wr1').value.trim(),lesson:$('#wr2').value.trim(),block:$('#wr3').value.trim(),priority:$('#wr4').value.trim(),adjust:$('#wr5').value.trim()};if(!entry.win&&!entry.lesson&&!entry.block&&!entry.priority&&!entry.adjust)return;data.weeklyReviews.unshift(entry);if(entry.priority)data.action=entry.priority;save();closeModal();toast('Week recalibrated');render()}
function sixMonthDinner(){let c=data.celebration||{};openModal(`<div class="dinnermodal"><div class="eyebrow">SIX MONTHS FROM NOW</div><h2>Everything Worked Out Dinner</h2><p>Choose a future Friday and make it the moment you’re celebrating everything that worked out.</p><label>Date</label><input id="cd" type="date" class="field" value="${esc(c.date||defaultCelebrationDate())}"><label>Who’s there?</label><input id="cw" class="field" value="${esc(c.who||'')}" placeholder="The people around the table"><label>Where are you celebrating?</label><input id="cwhere" class="field" value="${esc(c.where||'')}" placeholder="Restaurant, city, home…"><label>What worked out?</label><textarea id="cwhat" class="field" placeholder="What became real?">${esc(c.what||'')}</textarea><label>What are you proudest of?</label><textarea id="cproud" class="field" placeholder="What did you do to get here?">${esc(c.proud||'')}</textarea><button class="primary red" onclick="saveCelebration()">Put it on the horizon</button></div>`)}
function saveCelebration(){data.celebration={date:$('#cd').value,who:$('#cw').value.trim(),where:$('#cwhere').value.trim(),what:$('#cwhat').value.trim(),proud:$('#cproud').value.trim()};save();closeModal();toast('Future moment saved');render()}
function maybeSetup(){if(!data.setup?.dismissed&&setupStatus().some(x=>!x.done))setTimeout(setupModal,180)}
Object.assign(window,{visionPromptScreen,visionGuidedPrompts,buildGuidedVisionPrompt,prepareVisionPrompt,copyVisionPrompt,chooseGeneratedVision,saveGeneratedVision,showSavedVisionPrompt,visionActions,removeVisionBoard,autoSuggestVision,setupModal,setupGo,setupContinue,journeyGo,cueModal,setCueTrigger,saveCue,clearCue,aboutModal,reflectionTools,closeModal,editText,settingsModal,visionModal,saveVision,deleteVision,visionToGoal,goalModal,saveGoal,deleteGoal,goalDetail,toggleKey,carryAction,nextManifest,prevManifest,startManifestSession,dailyReflection,saveDailyReflection,weeklyReset,saveWeeklyReset,sixMonthDinner,saveCelebration,go,exportData,resetData,fuel,fuelModal,saveFuel,fuelDetail,deleteFuel});
